name: Test and coverage

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Build cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
      - name: Run tests (default features)
        run: cargo test --workspace --verbose
      - name: Run tests (--all-features)
        run: cargo test --workspace --all-features --verbose
      - name: Run tests (--no-default-features)
        run: cargo test --workspace --no-default-features --verbose
      - name: Generate coverage report (libtrayd)
        run: |
          cargo llvm-cov --all-features -p libtrayd --lcov --output-path lcov-libtrayd.info
      - name: Generate coverage report (trayd)
        run: |
          cargo llvm-cov --all-features -p trayd --lcov --output-path lcov-trayd.info
      - name: Generate coverage report (trayctl)
        run: |
          cargo llvm-cov --all-features -p trayctl --lcov --output-path lcov-trayctl.info
      - name: Generate coverage report (tray-tui)
        run: |
          cargo llvm-cov --all-features -p tray-tui --lcov --output-path lcov-tray-tui.info
      - name: Upload libtrayd coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          files: ./lcov-libtrayd.info
          flags: libtrayd
          name: libtrayd
          fail_ci_if_error: false
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload trayd coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          files: ./lcov-trayd.info
          flags: trayd
          name: trayd
          fail_ci_if_error: false
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload trayctl coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          files: ./lcov-trayctl.info
          flags: trayctl
          name: trayctl
          fail_ci_if_error: false
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload tray-tui coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          files: ./lcov-tray-tui.info
          flags: tray-tui
          name: tray-tui
          fail_ci_if_error: false
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
